apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vaultwarden
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
  - repoURL: https://guerzon.github.io/vaultwarden
    chart: vaultwarden
    targetRevision: 0.36.3
    helm:
      releaseName: vaultwarden
      valueFiles:
      - $values/deploy/apps/vaultwarden/values-dev.yaml
  - repoURL: https://github.com/hjr15/service-platform-template.git
    targetRevision: main
    ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: vaultwarden
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
